name: e2vid
channels:
  - pytorch
  - nvidia
  - conda-forge
  - robostack
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - setuptools=59.5.0
  - python=3.8
  - pip=21.3.1
  - numpy=1.21.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - tensorboard=2.6.0
  - ros-noetic-rosbag=1.15.9
  - opencv=4.5.2
  - pandas=1.5.2
  - scipy=1.10.0
